name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Update and install required packages
        run: |
          sudo apt update
          sudo apt install -y libc6-dev clang flex bison libssl-dev bc python3 zip unzip lld llvm p7zip-full jq
      - name: Prepare magiskboot
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          cd $GITHUB_WORKSPACE/output
          curl -L -o magiskboot.7z "https://github.com/xiaoxindada/magisk_bins_ndk/releases/download/magisk_bins-29001-cf09f1c1061138652a435cba3e675508730b0464/magisk_bins.7z"
          7z x magiskboot.7z
          cp ./native/out/x86_64/magiskboot .
          chmod +x magiskboot
          rm -rf ./out
      - name: Prepare boot.img
        run: |
          cd $GITHUB_WORKSPACE/output
          export lineageos_ver=$(curl -LfsG "https://download.lineageos.org/api/v1/lisa/nightly/0" | jq -r '.response[0].filename' | cut -d- -f3)   
          echo "RELEASE_TAG=$lineageos_ver" >> $GITHUB_ENV                                                                    
          curl -L -o boot.img "https://mirrorbits.lineageos.org/full/lisa/$lineageos_ver/boot.img"
      - name: Prepare required toolchains
        run: |
          mkdir -p $GITHUB_WORKSPACE/toolchains
          cd $GITHUB_WORKSPACE/toolchains
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth=1
      - name: Remove unnecessary tools
        run: |
          cd $GITHUB_WORKSPACE/toolchains/linux-x86
          latest_clang=$(find . -maxdepth 1 -type d -name "clang-r*" | sed 's|.*/||' | sort -Vr | head -n 1)
          echo "Latest Clang version detected: $latest_clang"
          
          for dir in clang-r*; do
            if [[ "$dir" != "$latest_clang" ]]; then
              echo "Removing $dir"
              rm -rf "$dir"
            fi
          done
          # Export path
          export PATH="$GITHUB_WORKSPACE/toolchains/linux-x86/$latest_clang/bin:$PATH"
      - name: Install KernelSU
        run: |
          cd $GITHUB_WORKSPACE
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s
      - name: Build Kernel
        run: |
          chmod +x build.sh
          ./build.sh
          cp $GITHUB_WORKSPACE/out/arch/arm64/boot/Image $GITHUB_WORKSPACE/output
      - name: Modify boot.img
        run: |
          cd $GITHUB_WORKSPACE/output
          ./magiskboot unpack boot.img
          rm -rf kernel
          mv Image kernel
          ./magiskboot repack boot.img
      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: new-boot
          path: /home/runner/work/android_kernel_xiaomi_sm8350/android_kernel_xiaomi_sm8350/output/new-boot.img
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: /home/runner/work/android_kernel_xiaomi_sm8350/android_kernel_xiaomi_sm8350/output/new-boot.img
